version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"  # Mapea el puerto 5000 del contenedor al puerto 5000 de tu m치quina host
    environment:
      - FLASK_ENV=development  # O producci칩n si es necesario
    volumes:
      - .:/app  # Sincroniza el c칩digo local con el contenedor
    restart: always  # Reinicia el contenedor autom치ticamente si se detiene