apiVersion: v1
kind: Service
metadata:
  name: ecocycle-db
spec:
  selector:
    app: ecocycle-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30000  # Un puerto en el rango 30000-32767
  type: NodePort